import type { Metadata } from "next";
import { Inter, Noto_Sans_JP } from 'next/font/google'
import "../styles/globals.scss";
import { Layout } from "@/layouts";
import clsx from "clsx";

const inter = Inter({ subsets: ['latin'] })
const notoSansJP = Noto_Sans_JP({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="ja">
      <body className={clsx(inter.className, notoSansJP.className)}>
        <Layout>{children}</Layout>
      </body>
    </html>
  );
}
